sub vcl_hit missing curly brackets
varnishd (varnish-6.0.6 revision 29a1a8243dbef3d973aec28dc90403188c1dc8e7)

Error:
Message from VCC-compiler:
Symbol not found.
('/opt/bitnami/varnish/etc/varnish/default.vcl' Line 281 Pos 1)
sub vcl_miss {
###-----------

Running VCC-compiler failed, exited with 2
VCL compilation failed
/opt/bitnami/varnish/scripts/ctl.sh : varnish could not be started